version: "3.6"

services:
  graphql:
    image: graphql-server
    build: graphql-server
    hostname: graphql
    ports:
      - "3000:3000"
    networks:
      - public_network
    environment:
      - NODE_ENV=development
      - DB_URI=haproxy
    depends_on:
      - haproxy
